spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: employee-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/emp/**
              filters:
                - RewritePath=/api/emp/(?<segment>.*), /api/emp/$\{segment}
                # Rate Limiting (10 requests per 60 seconds)
                - RequestRateLimiter=10,60
                # Circuit Breaker
                - CircuitBreaker=employeeCB,fallbackUri=http://localhost:8081/fallback


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Resilience4j Configurations
resilience4j:
  circuitbreaker:
    instances:
      employeeCB:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowSize: 10
  ratelimiter:
    instances:
      employeeRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 60s
        timeoutDuration: 2s


server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true