spring:
  application:
    name: reactive-employee-service
  mongodb:
    uri: mongodb://localhost:27017/crud1

server:
  port: 8085   # choose a different port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
